# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Leszczynski
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  John Leszczynski is a composer and programmer with an interest in birds and other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jrleszcz.github.com" # the base hostname & protocol for your site
twitter_username: jrleszcz
github_username:  jrleszcz

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
