# Trigger to update johnleszczynski.com when changes are pushed to Github branch.
steps:
  - id: Update Permissions
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'chmod'
    args: ['-v','-R', 'a+rw','.']
  - id: Build Jekyll Site
    name: 'jekyll/jekyll'
    args: ['jekyll','build']
    env: ['JEKYLL_ENV=production']
  # - id: Copy to bucket
  #   name: gcr.io/cloud-builders/gsutil
  #   args: ["-m", "rsync", "-r", "-c", "-d", "./_site", "gs://johnleszczynski-site"]
  - id: Deploy to App Engine
    name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: '10m'